### ISSUE TITLE
CRC Doesn't Match (Arduino Library Manager)

### ISSUE THREAD

**Issue by brendanmatkin** [adafruit/Adafruit_NeoPixel#104]
Hi, 

Arduino 1.6.8, OS X 10.11.4. 

When trying to install via Arduino Library Manager (either clicking update or selecting 1.0.5 + install), it fails. Stack trace:
```
CRC doesn't match. File is corrupted.
java.lang.RuntimeException: java.lang.Exception: CRC doesn't match. File is corrupted.
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$12(LibraryManagerUI.java:231)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: CRC doesn't match. File is corrupted.
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:77)
	at cc.arduino.contributions.libraries.LibraryInstaller.install(LibraryInstaller.java:97)
	at cc.arduino.contributions.libraries.ui.LibraryManagerUI.lambda$onInstallPressed$12(LibraryManagerUI.java:227)
	... 1 more
```

**Comment by brendanmatkin** [comment]
UPDATE: 

I deleted Adafruit_NeoPixel-1.0.5.zip from /Users/<username>/Library/Arduino15/staging/libraries/, restarted Arduino, and tried again. It worked as expected. I guess this is a non-issue, or is something github or library manager related causing this error?
